// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fhneddlnsiccucvmuftm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZobmVkZGxuc2ljY3Vjdm11ZnRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMjczNzgsImV4cCI6MjA3NDkwMzM3OH0.qYvtWVUVO4nSDxTw0TfnITOJJlo_-WHaGKFQn-D5-GI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true, // Mantém a sessão ativa
    storage: window.sessionStorage, // Usa sessionStorage para que a sessão expire ao fechar a aba
  },
});